import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { WindowMockup } from 'react-mockup'
import 'react-mockup/dist/index.css'
import { MdCode,MdDownload,MdPerson } from "react-icons/md";
import Header from './Header'

export default function Guide() {
    return (
        <div className={'container'}>
            <Head>
                <title>Installation Guide</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header/>
            <main className={styles.main}>
                <div className={styles.duoGrid}>
                    <section>
                        <h1 className={styles.title}>Shastra Guide</h1>
                        <h3>Here is the installation guid for Shastra OS</h3>
                    </section>
                    <div className={styles.aboutScroll}>
                        <h2>Installation</h2>
                        <h3>Download ISO file</h3>
                        <p>You can download ShastraOS from OSDN or Sourceforge mirrors.</p>
                        <div className={styles.buttonGap}>
                            <button className={styles.whiteBtn} onClick={() => { window.open('https://sourceforge.net/projects/shastra/files/latest/download', "_blank") }}><MdDownload className={styles.icon}/>Sourceforge</button>
                            <button className={styles.whiteBtn} onClick={() => { window.open('https://osdn.net/frs/redir.php?m=nchc&f=shastraos%2F77132%2FShastraDignity-Beta-2022.04.07-x86_64.iso', "_blank") }}><MdDownload className={styles.icon}/>OSDN</button>
                        </div>
                        <h3>Booting ISO using USB drive</h3>
                        <p>Download ISO file.</p>
                        <p>Insert USB drive into your PC</p>
                        <p>Use Software Balena Etcher (For Linux Users) and Rufus (For Windows Users)</p>
                        <p>After Booting ISO file, your system will be loaded.</p>
                        <h3>Installing into your PC</h3>
                        <p>Open Installer Application (you can just search it by pressing Windows/Command key.</p>
                        <p>Choose your option how you want to install and fill all details.</p>
                        <p>Go ahead and reboot after completing</p>
                        <p></p>
                        <hr />
                        <h2>Custominsing Shastra</h2>
                        <p>Shastra is highly customizable OS. You can easily change its theme. In tweaks application you will find these flavours as default.
                            
                            <br />
                            <ul>
                                <ol>Catppuccin Theme</ol>
                                <ol>Orchis Theme</ol>
                                <ol>Fluent Theme</ol>
                            </ul>
                            You can also mannually download other themes.
                        </p>
                        <div className={styles.carousel}>
                            <div className={styles.card}>
                            <WindowMockup src="/gnomescreen01.png" />
                            </div>
                            <div className={styles.card}>
                            <WindowMockup src="/screen01.png" />
                            </div>
                            <div className={styles.card}>
                            <WindowMockup src="/screen03.png" />
                            </div>
                        </div>
                        <hr />
                        <h2>More Guide</h2>
                        <h3>Lorem Ipsum</h3>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                            <br />
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                        </p>
                        <h3>Loprem Ipsum Dolor</h3>
                        <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                        </p>
                    </div>
                </div>
            </main>
        </div>
    )
}
