import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { WindowMockup } from 'react-mockup'
import 'react-mockup/dist/index.css'
import { MdCode,MdDownload,MdPerson } from "react-icons/md";
import Header from '../components/Header'
import Footer from '../components/Footer'

export default function Guide() {
    return (
        <div className={'container'}>
            <Head>
                <title>Installation Guide</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="keywords" content="Shastra, ShastraOS, Shastra linux, shastraos, Shastra OS, ShastraOS websites, Linux, Linux OS, OS, Gnome, Web3 OS, Web3 based OS, Web3 based Operating System, Vivek Pal, Arch Linux " />
                <meta name="theme-color" content="#317EFB"/>
                <link rel="icon" href="/favicon.ico" />
				<link rel='manifest' href='/manifest.json' />
                <link rel='apple-touch-icon' href='/icon-192x192.png' />
            </Head>
            <Header/>
            <main className={styles.main}>
                <div className={styles.duoGrid}>
                    <section>
                        <h1 className={styles.title}>Shastra Guide</h1>
                        <h3>Here is the installation guide for Shastra OS</h3>
                        <a href="#Install">Install</a>
                    </section>
                    <div className={styles.aboutScroll}>
                        <section id='Install'>
                            <h3>Guide to install ShastraOS</h3>
                            <div className="alignItems">
                                <button className={styles.blueBtn} onClick={() => { window.open('install', "_blank") }}><MdCode className={styles.icon}/>Insstallation Guide</button>
                            </div>
                        </section>
                    </div>
                </div>
            </main>
            <Footer/>
        </div>
    )
}
