import Head from "next/head";
import styles from "../styles/Home.module.css";
import { WindowMockup } from "react-mockup";
import "react-mockup/dist/index.css";
import { MdCode, MdDownload, MdPerson } from "react-icons/md";
import Header from "./Header";
import Footer from "./Footer";

export default function Guide() {
  return (
    <div className={"container"}>
      <Head>
        <title>Install Latest Shastra</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="author" content="Vivek Pal" />
        <meta
          name="keywords"
          content="ShastraOS, shastraos, shastra, shastra linux, vivek pal, akshat sharma, vivekpal, open source os, web3 os, decentralized os, blockchain on, blockchain, gnome os"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <div className={styles.duoGrid}>
          <section>
            <h1 className={styles.title}>Shastra Beta</h1>
            <h3>Here is the installation guide for Shastra Beta</h3>
            <a href="#Download">Download Latest iso file</a>
            <a href="#Verify">Verify the iso file</a>
            <a href="#Install">Install</a>
            <a href="#AfterInstall">After Installation</a>
            <a href="#Packages">ShastraOS Packages and applications</a>
          </section>
          <div className={styles.aboutScroll}>
            <section id="Download">
              <h3>Installation</h3>
              <h2>Download ISO file</h2>
              <p>
                You can download ShastraOS from OSDN (recommended) or
                Sourceforge mirrors.
              </p>
              <div>
                <button
                  className={styles.whiteBtn}
                  onClick={() => {
                    window.open(
                      "https://osdn.net/frs/redir.php?m=gigenet&f=shastraos%2F77132%2FShastra-Beta-2022.07.13-x86_64.iso",
                      "_blank"
                    );
                  }}
                >
                  <MdDownload className={styles.icon} />
                  Download
                </button>
                <br />
                <p>
                  You can also download Latest ISO file from ShastraOS{" "}
                  <a href="https://sourceforge.net/projects/shastra/files/latest/download">
                    Sourceforge mirror
                  </a>
                  . Sourceforge has the very latest ShastraOS Beta image file.
                  It can have some installation issues on some devices.
                </p>
              </div>
            </section>
            <section id="Verify">
              <h2>Verify your ShastraOS ISO file</h2>
              <p>
                While you can just download a hastraOS ISO image, can you be
                really sure that it&apos;s the right file? With a few simple
                steps, you can verify the integrity of any ShastraOS ISO.
                Here&apos;s how to do it.
                <br />
                <h4>Displaying the Checksum for a File</h4>
                To calculate an SHA256 checksum on a downloaded ISO file, use
                this SHA265 command.
                <br /> <code>md5sum -b &apos;filename&apos;</code> <br />
                For a MD5 checksum, use MD5 instead with the same -b option.
              </p>
              <h4>
                Here are the checksums for iso file
                Shastra-Beta-2022.07.12-x86_64.iso
              </h4>
              <p>
                File Size 2,201,399,296 bytes MD5 <br />
                7cf48a4decb01c76fb0ac56913219fc2 SHA1 <br />
                60b5cec7bca1fce0d156bd80097767a7c0a852ce SHA256 <br />
                71bd288e0c37adad8413cde809e1c1271397a3cff806f171fe89584156ee0353
              </p>
              <h3>Booting ISO using USB drive</h3>
            </section>
            <section id="Install">
              <p>
                Insert USB drive into your PC
                <br />
                Use Software Balena Etcher (For Linux Users) and Rufus (For
                Windows Users).
                <br />
                You can also use Ventoy (On other device)
              </p>
              <p>After Booting ISO file, your system will be loaded.</p>
              <h2>Installing into your PC</h2>
              <p>
                Calamares is a new system installation framework designed to be
                easily customized and used as the installation program for any
                Linux distribution. We use Calamares as our default installer in
                the live environment. Calamares is a user friendly and smooth
                installer. So that you can easily install your ShastraOS on a
                live environment and try out ShastraOS before really installing
                it to your machine. <br />
                ShastraOS installer does not require any internet connection by
                default, but we still prefer to have a good internet connection.
                <br />
              </p>
              <p>
                Open Installer Application (you can search it by pressing
                Windows/Mod key.)
              </p>
              <p>
                Select your preferred location for timing and other settings.
                <br />
                Now choose your default keyboard layout.
              </p>
              <h3>Partitioning scheme</h3>
              <p>
                Select your storage device, in which you want to install
                ShastraOS. <br />
                If the target hard drive has an operating system already
                installed, Calamares is able to auto-detect it and give you the
                appropriate options.
                <br />
                <strong>You will get four options to install ShastraOS</strong>
              </p>
              <h4>Install alongside of previous OS</h4>
              <p>
                Storage volume will be srinked for previous OS, and seprate
                volume partition will be created for ShastraOS on the same disk.
              </p>
              <h4>Replace a partition</h4>
              <p>
                A partition will replaced by ShastraOS and all your previous
                data will be erased. You will be able to choose a partition to
                replace.
              </p>
              <h4>Erase entire disk and install ShastraOS</h4>
              <p>
                This is the most recommended way to install ShastraOS in your
                machine. The disk you will choose will be erased and ShastraOS
                will installed on that particular disk.
                <br />
                You will be able to make a swap of 8gb or swap with hibernate.
                If you want to learn about what is swap, go and check out this
                article.{" "}
                <a href="https://averagelinuxuser.com/linux-swap/">
                  What is Linux Swap?
                </a>{" "}
                <br />
                Using swap is a very useful way to extend the RAM because it
                provides the necessary additional memory when the RAM space has
                been exhausted and a process has to be continued. It is
                especially recommended when you have less than 2Gb of RAM.
                Although in the end, everything depends on you.
              </p>
              <h4>Mannual Partitioning</h4>
              <p>This is only recommended for andvanced users.</p>
              <p>
                Select your own partitioning scheme. You must at least select an
                EFI(/boot/efi) partition and a root(/) partition.
              </p>{" "}
              <br />
              <h4>User Data</h4>
              <p>
                Username and passwords will be set here. You can set different
                passwords for normal use and for adminstrative tasks (root
                access). There&apos;s also an option to enable auto login at
                boot.
              </p>
              <strong>Now you will see summary in the next step.</strong>
              <p>
                Note that at this point no changes are physically done to the
                device. So don&apos;t be afraid if you made a mistake somewhere,
                you can go back and correct it.
              </p>
              When you click &apos;Install&apos;, there&apos;s no going back. So
              do take a careful look at the summary and see if you&apos;ve
              missed anything. After hitting install, the installation process
              will begin. It will take around 10-15 minutes. Once the
              installation is completed, you&apos;re given the option of
              rebooting your PC or staying in the live environment. Tick the
              Reboot Now box and press finish if you want to reboot.
            </section>

            <section id="AfterInstall">
              <h2>After Installation</h2>
              Once you reboot, you&apos;ll be greeted by the lock screen. Login
              and you are ready to use your ShastraOS <br />
              Here are some recommended things to do after installing ShastraOS.
              <h3>Update Your System</h3>
              <p>
                There are two ways to update your system and install your
                favorite applications.
                <br />
                Through terminal and GUI (Add/Remove Software).
              </p>
              <p>
                - Terminal: Open terminal and type{" "}
                <code>sudo pacman -Syyuu</code> to update pacman packages and{" "}
                <code>pamac update</code> to update AUR packages. <br />
                - GUI: Open Add/Remove Software, go to preferences, and enable
                AUR options in the third-party repository section. <br />- GUI:
                Open Add/Remove Software, go to the update section, and check
                your updates.
              </p>
              <h3>Enable Firewall Protection</h3>
              <p>
                First, check if you have ufw or gufw installed. <br />
                <code>sudo pacman -S ufw</code> or{" "}
                <code>sudo pacman -S gufw</code>
              </p>
              <p>
                To enable firewall protection, open terminal and type <br />
                <code>sudo ufw enable</code> or <code>sudo gufw enable</code>
              </p>
              <p>
                Or just search firewall, and turn it on. If you are unable to
                find install gufw.
              </p>
              <h3>Set the fastest mirror</h3>
              Open the Terminal emulator and type the following command:
              <code>sudo pacman-mirrors --fasttrack</code>
            </section>

            <section id="Backups">
              <h2>Backups</h2>
              <p>
                You can backup your system using the Backups Application. <br />
                And protect yourself from any data loss. <br />
                You can also restore any previous backup of ShastraOS or Arch
                Linux.
              </p>
            </section>

            <h2>Customizing ShastraOS</h2>
            <section id="Customization">
              <div className={styles.carousel}>
                <div className={styles.card}>
                  <WindowMockup src="/gnomescreen01.png" />
                </div>
                <div className={styles.card}>
                  <WindowMockup src="/screen01.png" />
                </div>
                <div className={styles.card}>
                  <WindowMockup src="/screen03.png" />
                </div>
              </div>
              <hr />

              <p>
                Shastra is a highly customizable OS. You can easily change its
                theme and Dark Mode. If you want to change the dark mode, Go to
                settings, then appearance, and select dark mode and wallpapers.
                In the tweaks application, you will find these themes as
                default.
                <br />
                <ul>
                  <ol>Orchis Theme</ol>
                  <ol>Fluent Theme</ol>
                </ul>
                You can also manually download other themes from{" "}
                <a href="https://www.gnome-look.org/browse/">Gnome-Look</a>
              </p>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
