/* eslint-disable react/jsx-no-undef */

import Head from "next/head";
import styles from "../styles/Home.module.css";
import "react-mockup/dist/index.css";
import { MdCode, MdOutlineDownload, MdLogin } from "react-icons/md";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { Widget, PopupButton } from "@typeform/embed-react";

export default function Guide() {
  return (
    <div className={"container"}>
      <Head>
        <title>ShastraOS Hacktoberfest 2022</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="author" content="Vivek Pal" />
        <meta
          name="keywords"
          content="Shastra, ShastraOS, Shastra linux, shastraos, Shastra OS, ShastraOS websites, Linux, Linux OS, OS, Gnome, Web3 OS, Web3 based OS, Web3 based Operating System, Vivek Pal, Arch Linux "
        />
        <meta name="theme-color" content="#317EFB" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="/manifest.json" />
        <link rel="apple-touch-icon" href="/icon-192x192.png" />
      </Head>
      <Header />

      <main className={styles.main}>
        <div className={styles.duoGrid}>
          <section className={styles.padding2em}>
            <h1 className={styles.title}>Shastra Open Source</h1>
            <h2>Contribute to ShastraOS project this Hacktoberfest.</h2>
            <p className={styles.description}>
              Anyone can help us by contributing to the Shastra Project.
              ShastraOS is open for Hacktoberfest 2022. Take part in ShastraOS
              Hacktoberfest 2022 and get crazy swaggs and perks.
            </p>
            <div className={styles.buttonGap}>
              <button
                className={styles.whiteBtn}
                onClick={() => {
                  window.open("https://forms.office.com/r/DVReTBS2Wu", "_blank");
                }}
              >
                <MdCode className={styles.icon} />
                Sign Up for ShastraOS Hacktoberfest
              </button>
              <button
                className={styles.whiteBtn}
                onClick={() => {
                  window.open("https://github.com/shastra-os", "_blank");
                }}
              >
                <MdCode className={styles.icon} />
                GitHub
              </button>
              <button
                className={styles.whiteBtn}
                onClick={() => {
                  window.open("https://gitlab.com/shastraos", "_blank");
                }}
              >
                <MdCode className={styles.icon} />
                GitLab
              </button>
            </div>
          </section>
        </div>
        <br></br>
        <br></br>
        <br></br>
        <br></br>
      </main>
      <Footer />
    </div>
  );
}
