name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - '**/.md'
  workflow_dispatch:

jobs:
  typescript:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install yarn
        uses: yarn/action-setup@v2.2.2
        with:
          version: 1.22

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: 'yarn'
          
      - name: Install yarn
        uses: yarn/action-setup@v2.0.1
        with:
          version: 1.22
